### PR TITLE
[VERSION] Use v0.7 for stable build

### PR DESCRIPTION
**Pull request by tqchen**
cc @leandron @junrushao1994 @areusch

### CODE REVIEW

**Review by areusch — APPROVED** [review]

**Comment by areusch** [comment]
are the failures expected @tqchen?

**Comment by tqchen** [comment]
Looking, seems conda build have some problems on the main due to conda prune not working, looking into that.

**Comment by tqchen** [comment]
https://github.com/tlc-pack/tlcpack/pull/86 should fix the conda prune problem

**Comment by tqchen** [comment]
I would actually suggest we merge this so at least the wheel packages can be updated to the v0.7. then figure out the conda part in main in case there are still followup issues

**Comment by areusch** [comment]
i'm good with that. just to confirm my understanding, we should be building 0.8 for stable build at some point, right? just right now the infra only supports building one at a time?

**Comment by tqchen** [comment]
Right, the assumption was as we build v0.8 the v0.7 is already been built and there isn't a need to update that, as that changes we  need to update the infra

**Pull request merged**
