### PR TITLE
Update retry with exp backoff

### PR DESCRIPTION
**Pull request by tqchen**

### CODE REVIEW

**Comment by Hzfengsy** [comment]
cc @tqchen. Any update?

**Comment by tqchen** [comment]
The error was not related to the change but some upstream change in Arm ethos libraries: perhaps we can merge this in first

**Comment by ashutosh-arm** [comment]
https://github.com/tlc-pack/tlcpack/pull/152 was merged last week with an update to Arm(R) Ethos(TM)-N NPU driver. The CI first downloads latest docker image from `tlcpack/package-cpu` which still seems to contain an older driver version. @driazati any reason why this is the case?

**Review by driazati — APPROVED** [review]
We can just merge this now and fix the failure in a follow up, if it's just a Docker update https://github.com/tlc-pack/tlcpack/blob/main/.github/workflows/wheel_manylinux_pypi.yaml#L23 is the place, the `package-*` images are automatically built and uploaded to https://hub.docker.com/u/tlcpack

**Comment by ashutosh-arm** [comment]
Thanks @driazati. I will raise a PR with hash updates.

**Pull request merged**
