### PR TITLE
[ETHOSN] Update NPU driver stack to v22.05

### PR DESCRIPTION
**Pull request by lhutton1**
Updates the driver stack version to v22.05.

cc @Leo-arm @leandron

### CODE REVIEW

**Review by leandron — APPROVED** [review]
Thanks for the PR @lhutton1.

**Review by leandron — CHANGES_REQUESTED** [review]
Just blocking it so that we don't accidentally merge before @lhutton1 let us know.

**Comment by lhutton1** [comment]
Can we merge this now the docker images are updated?

**Review by leandron — APPROVED** [review]
LGTM, thanks @lhutton1

**Pull request merged**
