### PR TITLE
[ETHOSN] Add support for Ethos-N 21.08 driver stack release

### PR DESCRIPTION
**Pull request by Leo-arm**
- Updated Ethos-N driver stack to 21.08

### CODE REVIEW

**Comment by leandron** [comment]
CI is broken on this PR, and talking to @Leo-arm we realised that actually the Docker images are not rebuilt for every PR to test these changes, so we'll need to:
1. rebuild the images
2. submit another PR bumping the image version
3. re-run CI here
4. merge this

cc @tqchen @Mousius @areusch FYI

**Comment by areusch** [comment]
i think @driazati was also discussing this shortcoming: https://discuss.tvm.apache.org/t/rfc-rebuild-docker-images-per-commit/12047

would be great to get some comments there @leandron et al

**Comment by leandron** [comment]
> i think @driazati was also discussing this shortcoming: https://discuss.tvm.apache.org/t/rfc-rebuild-docker-images-per-commit/12047
> 
> would be great to get some comments there @leandron et al

Does @driazati's RFC cover the `tlcpack/package-*` images? I don't think it does, right? Despite that, I'm in 100% favour of rebuilding docker images in TVM. I'll write some points in the Forum later.

The issue being discussed here, should be gone after #92 is merged.

**Comment by leandron** [comment]
Thanks @Leo-arm

**Pull request merged**
